-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    GENDER,
    COUNT(DISTINCT SALE.USER_ID) AS USERS
FROM ONLINE_SALE AS SALE
JOIN USER_INFO AS INFO
ON SALE.USER_ID = INFO.USER_ID
WHERE NOT GENDER IS NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER
